language: node_js
node_js:
 - "0.12"
before_script:
- npm install -g karma-cli
- npm install -g bower
- bower install
script:
 - npm run-script test
notifications:
 email: - false
after_failure:
 - print_surefire_reports.sh